### PR TITLE
Add CMake Support

### PR DESCRIPTION
**Pull request by LeviSchuck**
Hopefully this will work in one try

### CODE REVIEW

**Comment by jroweboy** [comment]
Hmmm well this doesn't work on my machine, BUT I still think this code can be used still. I feel that after I remove the Regex requirements we can use this as that was what cause the error. Wait until I get that change pushed and then we can merge this code in and get rid of the makefile

**Comment by robhobbes** [comment]
Here's a reason why forking is inferior compared to branching: I have to go git clone Levi's fork instead of being able to just checkout his branch from the repo I already have   :(

**Comment by cletusw** [comment]
No, you should just be able to add his fork as a remote from your existing
repo and pull branches into the same place.

2014-03-25 11:35 GMT-06:00 Robert Hickman notifications@github.com:

**Comment by cletusw** [comment]
Try:
git remote add levi https://github.com/blah/blah.git
git checkout -b levi-cmake levi/master (or whatever branch he called it on
his fork)

2014-03-25 11:37 GMT-06:00 Clayton Watts cletusw@gmail.com:

**Comment by cletusw** [comment]
This just worked for me:
git remote add levi https://github.com/ https://github.com/blah/blah.git
kloplop321/oxidize.git
git fetch levi
git checkout -b levi-trie levi/master

Clayton

2014-03-25 11:41 GMT-06:00 Clayton Watts cletusw@gmail.com:

**Comment by robhobbes** [comment]
@cletusw Sweet! Thanks. I didn't know that.

@kloplop321 So I have never used cmake. What exactly should I do to try building the project using cmake?

**Comment by jroweboy** [comment]
The typical cmake workflow is 

```
cmake ./
make
```

CMake's goal is to have an easy way to generate cross platform build files, so on mac it will make a xcode project, windows visual studio, and unix/linux it'll use make.

**Comment by robhobbes** [comment]
@jroweboy If that is indeed the work flow, then it doesn't work on my system either. It breaks on rust_mustache... "No targets specified and no makefile found."

**Comment by robhobbes** [comment]
Turns out it works for me. I just had empty submodule directories.

**Comment by LeviSchuck** [comment]
Guys.. don't cmake in the source directory..

``` bash
cd build
cmake ..
make
```

**Comment by robhobbes** [comment]
So, my question is, if we switch to trie-based routing, will we need to make any changes, or will it still build just fine using cmake? (If I recall, I didn't need to modify the Makefile to make trie-routing work, I just needed to add a line to the route module)

If it will continue to work and we won't need to mess with the CMakeLists.txt file and if this is working for everyone else (except @jroweboy), then we should probably merge this (unless we have a good idea of why it isn't working for @jroweboy).

If nobody comments in opposition, then I will merge it later tonight.

**Comment by LeviSchuck** [comment]
It will work, but whenever you add new files, you might have to redo `cmake ..` so that it becomes aware of the files.

`rustc` seems to handle all the magic when it comes to finding the files to compile inside the crate, but that does not mean the build system will notice new files automatically.

**Pull request merged**
